Repository UCATLAS/xAODAnaHelpers, pull requests merged in 2018-05, with the labels that each got.

#1200 Add xsec for Powheg+Pythia8 ttbar and low mass dijet+ISR samples.
  data/metadata/dijetisr_crosssections_13TeV.txt
  data/metadata/ttbar_allhad_crosssections_13TeV.txt
Labels: xsec

#1199 Fix BJetEfficiencyCorrector loop for uncalibrated btaggers
  Root/BJetEfficiencyCorrector.cxx
Labels: btagging, bug

#1204 Add disabledTriggers List to Output Ntuples.
  Root/BasicEventSelection.cxx
  Root/HelpTreeBase.cxx
  xAODAnaHelpers/HelpTreeBase.h
Labels: ntuple, trigger

#1209 More jet scales
  Root/JetContainer.cxx
  xAODAnaHelpers/JetContainer.h
Labels: enhancement, fatjet
