Repository UCATLAS/xAODAnaHelpers, pull requests merged in 2018-10, with the labels that each got.

#1250 Custom jvt cuts need to use detector-eta
  Root/JetSelector.cxx
Labels: enhancement

#1252 Update MuonCalibrator to use MuonCalibrationPeriodTool
  Root/MuonCalibrator.cxx
  xAODAnaHelpers/MuonCalibrator.h
Labels: enhancement, muon

#1245 Add MC/MC scale factors to b-tagging.
  Root/BJetEfficiencyCorrector.cxx
  Root/HelperFunctions.cxx
  xAODAnaHelpers/BJetEfficiencyCorrector.h
  xAODAnaHelpers/HelperFunctions.h
Labels: btagging, enhancement

#1263 add a way to register outputs
  python/config.py
  scripts/xAH_run.py
Labels: enhancement
