Repository UCATLAS/xAODAnaHelpers, pull requests merged in 2019-11, with the labels that each got.

#1379 Wrap m_prwActualMu20XXFile settings in PathResolverFindCalibFile.
  Root/BasicEventSelection.cxx
Labels: prw

#1378 BJetEfficiencyCorrector now loads SF variation per jet container
  Root/BJetEfficiencyCorrector.cxx
Labels: btagging

#1381 Fix bug in MuonInFatJetCorrector when making muon-trackjet ElementLink.
  Root/MuonInFatJetCorrector.cxx
Labels: bug

#1391 fix up xAHRun for when there's no lsb_release
  scripts/xAH_run.py
Labels: bug
