Repository UCATLAS/xAODAnaHelpers, pull requests merged in 2020-03, with the labels that each got.

#1416 docs: Mention list of input paths is newline separated
  python/cli_options.py
  scripts/xAH_run.py
Labels: documentation

#1425 Add AOD-level alternate sum of weights for to meta-data.
  Root/BasicEventSelection.cxx
  xAODAnaHelpers/BasicEventSelection.h
Labels: MetaData, enhancement

#1429 Harmonize m_pass_max
  Root/JetSelector.cxx
  Root/PhotonSelector.cxx
  Root/TauSelector.cxx
  Root/TrackSelector.cxx
  Root/TruthSelector.cxx
Labels: enhancement
