Repository UCATLAS/xAODAnaHelpers, pull requests merged in 2022-10, with the labels that each got.

#1574 feat: Support sweeping into master
  .github/workflows/cherry-pick.yml
Labels: sweep-r22

#1576 fix: Sweeping only occurs to master, not to r22/master
  .github/workflows/cherry-pick.yml
Labels: sweep-r22

#1573 Bugfix: LHCut not updated if multiple instances of ElectronSelector are called
  Root/ElectronSelector.cxx
Labels: sweep-r21

#1578 Bugfix: LHCut not updated if multiple instances of ElectronSelector are called
  Root/ElectronSelector.cxx
Labels: cherry-pick
